# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-16 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.PositiveIntegerField(default=2)),
                ('tweet', models.TextField(verbose_name='Tweet')),
                ('tweet_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.CustomUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TweetLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.PositiveIntegerField(default=2)),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwitter.Tweet')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.CustomUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
