# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-16 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.PositiveIntegerField(default=2)),
                ('mobile', models.CharField(max_length=12, verbose_name='Mobile No')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Country')),
                ('gender', models.CharField(choices=[(b'male', b'Male'), (b'female', b'Female')], default=' ', max_length=10, verbose_name='Gender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
